.TH LPRM 1
.UC
.SH NAME
lprm \- delete jobs from the lineprinter queue
.SH SYNOPSIS
\fBlprm\fR [ option ] [ job_numbers ... ] [ user_names ... ]
.SH DESCRIPTION
\fILprm\fR deletes the
.IR file s
from the print queue.
.I Lprm
will attempt to delete members whose job numbers or user names
have been entered with the command.
No one except the super-user may remove another user's files.
The following
.IR option s
are available:
.TP \w'-Pprinter\ \ \ 'u
.B \-
Delete all jobs owned by the issuer of the command.
.TP
.B \-\^Pprinter
Delete jobs from the queue of the alternate
printer
.IR printer .
.SH FILES
.ta 2i
/usr/spool/lpd/lock
.br
/usr/spool/lpd/cf*	data file
.br
/usr/spool/lpd/df*	daemon control file
.br
/usr/spool/lpd/tf*	temporary version of control file
.DT
.SH SEE ALSO
lpq(1), lprm(1), printcap(5), lpd(8), ulf(8)
