all:;

install:
	install -c lpq.1 ${DESTDIR}/usr/man/man1/lpq.1
	install -c lpr.1 ${DESTDIR}/usr/man/man1/lpr.1
	install -c lprm.1 ${DESTDIR}/usr/man/man1/lprm.1
	install -c printcap.5 ${DESTDIR}/usr/man/man5/printcap.5
	install -c ulf.8 ${DESTDIR}/usr/man/man8/ulf.8

clean:;
