#!/bin/sh -

#	@(#)netstart	5.2 (Berkeley) 7/16/88

INET=`/etc/testnet`
if [ $INET = YES ]; then
	echo Assuming NETWORKING system ...		>/dev/console 2>&1
else
	echo Assuming non-networking system ...		>/dev/console 2>&1
fi
export INET

# DON'T EVEN THINK ABOUT RUNNING ROUTED ON A PDP-11!!!  Just set routedflags
# to "NO" and set up a default gateway below.
#
routedflags=NO
rwhod=NO
named=NO

# myname is my symbolic name
# my-netmask is specified in /etc/networks
# my-default-address should be set to some machine where you
#	want to send all your packets, by default.
#
hostname=myname.my.domain
netmask=my-net-mask
broadcast=my-broadcast-address
default=my-default-address

hostname $hostname					>/dev/console 2>&1
hostid $hostname					>/dev/console 2>&1

if [ $INET = YES ]; then
	# /etc/ifconfig imp0 inet netmask $netmask $hostname broadcast $broadcast up -trailers >/dev/console 2>&1
	# /etc/ifconfig en0 inet netmask $netmask $hostname broadcast $broadcast up -trailers >/dev/console 2>&1
	# /etc/ifconfig il0 inet netmask $netmask $hostname broadcast $broadcast up -trailers >/dev/console 2>&1
	# /etc/ifconfig qe0 inet netmask $netmask $hostname broadcast $broadcast up -trailers >/dev/console 2>&1
	/etc/ifconfig lo0 inet localhost up -trailers	>/dev/console 2>&1

	/etc/route add $hostname localhost 0		>/dev/console 2>&1
	/etc/route add default $default 1		>/dev/console 2>&1
fi
