.TH LPR 1
.UC
.SH NAME
lpr \- line printer spooler
.SH SYNOPSIS
\fBlpr\fR [ option ] ... [ file ] ...
.SH DESCRIPTION
\fILpr\fR causes the
.IR file s
to be queued for printing on a line printer.
If no files are named, the standard input is read.
The following
.IR option s
are available:
.TP \w'-Pprinter\ \ \ 'u
.B \-\^r
Remove the file when it has been queued.
.TP
.B \-\^c
Copy the file to insulate against changes that may happen before printing.
.TP
.B \-\^m
Report by
.IR mail (1)
when printing is complete.
.TP
.B \-\^Jname
Print
.I name
instead of file name on header page.
.TP
.B \-\^p
Pipe each file through pr before printing it.
.TP
.B \-\^hname
Use
.I name
instead of file name on pr's header.
.TP
.B \-\^inn
Indent output
.I nn
spaces (8 if just -i).
.TP
.B \-\^nnn
Print
.I nn
copies of each file.
.TP
.B \-\^Pprinter
Route output to alternate printer
.IR printer .
.SH FILES
.ta 2i
/usr/spool/lpd/lock
.br
/usr/spool/lpd/cf*	data file
.br
/usr/spool/lpd/df*	daemon control file
.br
/usr/spool/lpd/tf*	temporary version of control file
.br
/usr/adm/lpacct	accounting records
.DT
.SH SEE ALSO
lpq(1), lprm(1), printcap(5), lpd(8), ulf(8)
