all:;

cp:
	cp lpq.1 ${DESTDIR}/usr/man/man1/lpq.1
	cp lpr.1 ${DESTDIR}/usr/man/man1/lpr.1
	cp lprm.1 ${DESTDIR}/usr/man/man1/lprm.1
	cp printcap.5 ${DESTDIR}/usr/man/man5/printcap.5
	cp ulf.8 ${DESTDIR}/usr/man/man8/ulf.8

clean:;
