.TH FORTUNE 6 "1 February 1983"
.UC 4
.SH NAME
fortune \- print a random, hopefully interesting, adage
.SH SYNOPSIS
.B /usr/games/fortune
[
.B \-
] [
.B \-almosw
]
..[ -f file ]
.SH DESCRIPTION
.I Fortune
with no arguments prints out a random adage. The flags mean:
.PP
.TP 5
.B \-a
Select from both standard and potentially offensive messages and limericks.
.TP 5
.B \-f
Use the given file as the fortune file.  This file
must have been created by the program strfile.
.TP 5
.B \-l
Select from long messages only.
.TP 5
.B \-m
Select from potentially offensive limericks.
.TP 5
.B \-o
Select from potentially offensive messages.
.TP 5
.B \-s
Select from short messages only.
.TP 5
.B \-w
Waits before termination
for an amount of time calculated from the number of characters in the message.
This is useful if it is executed as part of the logout procedure
to guarantee that the message can be read before the screen is cleared.
.PP
.SH FILES
/usr/games/lib/fortunes.dat
.SH AUTHOR
Original: Ken Arnold
Rewrite: Keith Bostic
