! "eatblinker" (cells 54 length 21 width 51 generation 0)
! This shows a reaction in which a set of traffic lights is tugged around by
! a string of blinkers.  The traffic lights eats each blinker it encounters,
! leaving no debris.
10k26h@!
................OOO
.
..............O.....O..........O...............O
..............O.....O.OOO......O......OOO......O
..............O.....O..........O...............O
OOO
................OOO
.
.................................................O
.................................................O
.................................................O
.
.O
.O
.O
.
.
................................................OOO
...O...............O...............O
...O......OOO......O......OOO......O......OOO
...O...............O...............O
