! "gun1" (cells 44 length 12 width 36 generation 30)
! This is the original glider gun, which creates a glider every 30 generations.
! This was the first object found which grew without bound.  It is composed of
! two identical but phase-shifted shuttle elements which collide properly to
! produce a glider.
11k10h@!
............O
............O.O
OO...........O.O.......O
OO...........O..O......OO
.............O.O..OO....OO
............O.O...OO....OOO.......OO
............O.....OO....OO........OO
.......................OO
.......................O
...........O
..........O
..........OOO
