! "rake" (cells 63 length 19 width 26 generation 20)
! This is the "space rake", which is a puffer train which generates a
! dense stream of forward-traveling gliders.  A new glider is generated
! every 20 generations.  The debris near the rearward spaceship is
! transformed into a glider.
9k23h@!
...............OO.....OOOO
.............OO.OO...O...O
.............OOOO........O
..............OO.....O..O
.
....................O
...............O...O..O
..............OO.......O
...............OO......O
................OO....OO
O.O..................O
O..O..............OO
.
.OOO
......................OOOO
....O..O.............O...O
........O................O
....O...O............O..O
.....OOOO
