! "relay" (cells 29 length 7 width 35 generation 0)
! This shows a glider which travels back and forth between two pentadecathlons.
! The distance between the endpoints can be made arbitrarily large.  This is
! one of three known "shuttles", but is isn't as useful as the others (which
! form the engines of the two kinds of glider guns).
4k17h@!
..O....O
OO.OOOO.OO
..O....O
................O
.................OO........O....O
................OO.......OO.OOOO.OO
...........................O....O
