! "shuttles" (cells 49 length 11 width 62 generation 0)
! These are two of the three known shuttles (the third is "relay" in which
! a glider travels back and forth between two pentadecathalons).  These are
! the "engines" which power the two kinds of glider guns.  The shuttle on the
! left has a period of 30.  The shuttle on the right has a period of 46.
5k29h@!
..................................................O
.................................OO...............OO........OO
.........OO......................OO................OO.......OO
.........O..O.....................................OO
.............O
OO...........O......OO
OO...........O......OO
.........O..O.....................................OO
.........OO......................OO................OO.......OO
.................................OO...............OO........OO
..................................................O
