! "switch" (cells 11 length 7 width 28 generation 0)
! This is the incredible switch engine.  This puffer train travels diagonally
! at 1/12 the speed of light towards the upper left with a period of 96.
! It's only exhaust is many sets of blocks arranged in a zig-zag.  This is the
! smallest known object which grows without bound (11 cells).  The block to
! the right is necessary to stabilize the exhaust.  Without it, the engine is
! killed by the untamed exhaust before it reaches 12 full periods.
1k@!
.O.O
O
.O..O
...OOO
.
..........................OO
..........................O
