.TH GETPID 2 
.UC
.SH NAME
getpid, getppid  \-  get process identification
.SH SYNOPSIS
.B pid = getpid();
.br
.B ppid = getppid();
.SH DESCRIPTION
.I Getpid
returns the process ID of the current process.
Most often it is used to generate uniquely-named temporary files.
.I Getppid
returns the process ID of the parent of the current process.
.SH "SEE ALSO"
mktemp(3)
.SH ASSEMBLER
(getpid = 20.)
.br
.B sys getpid
.br
(pid in r0)
.br
(ppid in r1)
