.\" Copyright (c) 1983 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
.\"
.\"	@(#)rtp.2	2.3 (Berkeley) 1/22/87
.\"
.TH RTP 2 "January 22, 1987"
.UC 2
.SH NAME
rtp \- make/unmake a real time process (2BSD)
.SH SYNOPSIS
.nf
.ft B
rtp(flag)
int flag
.fi
.ft R
.SH DESCRIPTION
If the
.I flag
argument is non-zero the process is marked as a
.I real time
process.
If the argument is zero,
the processes real time status is revoked.
.PP
A real time process
does not compete for system resources in the normal manner; instead,
a real time process is considered locked into physical memory
by the swap scheduler and
receives exclusive use of the central processor
from the process scheduler
whenever the real time process is in a executable state.
Furthermore, other processes which
previously were non-preemptable but had the potential of consuming
relatively large amounts of cpu time are made preemptable by
.IR rtp .
There can be only one real time process active at any time.
.PP
It is the responsibility of the real time process to see to it that
use of the cpu is relinquished often enough and long enough for
other normal UNIX processes to run.
For this reason only the
super-user
is allowed to change the mode of a process via
.I rtp.
.SH ERRORS
.TP 15
[EINVAL]
The kernel has not been compiled with the RTP option.
.TP 15
[EPERM]
The caller is not the super-user.
.TP 15
[EBUSY]
A real time process already exists.
.SH "SEE ALSO"
lock(2), setpriority(2)
.SH AUTHOR
Thomas Ferrin, University of California, San Francisco
.SH BUGS
.I Rtp
is unique to the PDP-11 and 2BSD; its use is discouraged.
