.TH DN 4 
.UC
.SH NAME
dn \- DN-11 ACU interface
.SH DESCRIPTION
The files
.IR cua0 ,
etc. refer to the units of a DN-11 ACU interface, and are write-only.
The codes for the phone numbers are:
.TP
0-9
dial 0-9
.br
.ns
.TP
.B :
dial *
.br
.ns
.TP
.B ;
dial #
.br
.ns
.TP
\-
2 second delay for second dial tone
.br
.ns
.TP
<
end-of-number
.DT
.PP
It is recommended that an end of number
code be given even though not all
ACU's actually require it.
.SH "SEE ALSO"
cu(1), uucp(1C)
.SH FILES
.ta 2i
/dev/cua0	(normally connected to /dev/cul0).
