.TH INTRO 4
.UC
.SH NAME
intro \- introduction to device special files
.SH DESCRIPTION
This section describes the special files that refer to peripheral devices
and related driver functions available on the system.
The DIAGNOSTICS section lists messages which may appear on the console
and in the system error log due to errors in device operation.
.SH FILES
.ta 2i
/dev/console	console tty
.br
/usr/adm/messages	system error log
.SH "SEE ALSO"
intrlve(4)	file system interleaving information
