.TH SWAP 4 
.UC
.SH NAME
swap \- swap device
.SH DESCRIPTION
This file refers to the swap device in use by the system.
It should be linked to the special file for the disk or disk partition
on which the system swaps.
It is used by programs that wish to read from
the swap device without knowing its real name.
.SH FILES
/dev/swap
.SH "SEE ALSO"
ps(1), w(1)
