.TH COUNT 1
.UC
.SH NAME
count \- count items in a file
.SH SYNOPSIS
.B count
[
.B \-lwcpt
]
[ file ... ]
.SH DESCRIPTION
.I Count
counts all the characters, words, lines, and pages
in a list of files.
The time needed to print the file at 300 baud is also determined.
A readable description of the results
is produced on the standard output, one line per file,
plus a total if more than one file is given.
If no files are given, the standard input is read.
.PP
The options restrict the output to lines, words, characters, pages,
and time, respectively.
Any combination in any order may be specified.
.SH AUTHOR
Mark Horton
.SH BUGS
The time does not take into account delays caused by padding bits,
expansion of tabs, or slow systems.
