.TH DF 1
.UC
.SH NAME
df \- disk free
.SH SYNOPSIS
.B df
[
.B \-i
] [
.B \-l
] [ filesystem ... ] [ file ... ]
.SH DESCRIPTION
.I Df
prints out the number of free blocks
available on the specified
.I filesystem,
e.g. ``/dev/rp0a'',
or on the file system in which the specified
.I file,
e.g. ``$HOME'',
is contained.
If no file system is specified,
the free space on all of
the normally mounted file systems
is printed.
.PP
The reported numbers are in file system block units; currently each file system
block is 1024 bytes long.
.PP
Other options are:
.TP
.B \-\^i
Report also the number of inodes which are used and free.
.TP
.B \-\^l
examines also the free list, double checking that the
summary number in the file system superblock is correct.
.SH FILES
.ta 2i
/etc/fstab	list of normally mounted file systems
.SH "SEE ALSO"
fstab(5), icheck(8), quot(8)
.SH BUGS
Does not know that ``/'' is a mounted file system.
