.TH DU 1 
.UC
.SH NAME
du  \-  summarize disk usage
.SH SYNOPSIS
.B du
[
.B \-a
] [
.B \-s
] [ name ... ]
.SH DESCRIPTION
.I Du
gives the number of 1024-byte blocks contained in all files
and (recursively) directories within each specified directory or
file
.IR name .
If
.I name
is missing,
`\fB.\fP'
is used.  Options are:
.TP
.B \-\^a
Generate an entry for each file.
.TP
.B \-\^s
Give a grand total only.
.PP
Absence of either causes an entry to be generated for
each directory only.
A file which has two links to it is only counted once.
.SH BUGS
Non-directories
given as arguments (not under
.B \-a
option) are not listed.
.br
If there are too many distinct linked files,
.I du
counts the excess files multiply.
