.TH FILE 1 
.UC
.SH NAME
file \- determine file type
.SH SYNOPSIS
.B file
[ \-\fBf\fP name ]
.br
.B file
file1 ... filen
.SH DESCRIPTION
.I File
performs a series of tests on each argument
in an attempt to classify it.
If an argument appears to be ASCII,
.I file
examines the first 512 bytes
and tries to guess its language.
.PP
If \-f is used,
.I file
reads its argument list from the file
.IR name .
.SH BUGS
It often makes mistakes.
In particular it often suggests that
command files are C programs.
