.TH FLEECE 1
.UC
.SH NAME
fleece \- look for files in home directories
.SH SYNOPSIS
.B fleece
name
.SH DESCRIPTION
.I Fleece
looks for the named file in every home directory on the system
and makes a list on standard output of those which exist.
.SH FILES
.ta 2i
/etc/passwd	to find home directories
.SH AUTHOR
Kurt Shoens
