.TH LPR 1
.UC
.SH NAME
lpr \- line printer spooler
.SH SYNOPSIS
\fBlpr\fP [ option ] ... [ file ] ...
.SH DESCRIPTION
\fILpr\fP causes the \fIfile\fP\|s to be queued for printing on a line
printer.  If no files are named, the standard input is read.  The
following options are available:
.PP
.ta 4m +\w'-m    'u
.di xx
		\ka
.br
.di
.in \nau
.ti0
	\fB\-\^r\fP	Remove the file when it has been queued.
.ti0
	\fB\-\^c\fP	Copy the file to insulate against changes that may happen
before printing.
.ti0
	\fB\-\^m\fP	Report by \fImail\fP\|(1) when printing is complete.
.ti0
	\fB\-\^n\fP	Do not report by mail.  This is the default option.
.PP
.SH FILES
.ta 2i
/usr/spool/lpd/lock	lock file
.br
/usr/spool/lpd/cf*	data file
.br
/usr/spool/lpd/df*	daemon control file
.br
/usr/spool/lpd/tf*	temporary version of control file
.br
.SH SEE ALSO
lpd(8)
