.TH NEWALIASES 1
.UC
.SH NAME
newaliases \- rebuild the data base for the mail aliases file
.SH SYNOPSIS
.B newaliases
.SH DESCRIPTION
.I Newalises
rebuilds the random access data base for the mail aliases file.
It must be run each time the alias file is changed in order
for the change to take effect.
.SH FILES
.ta 2i
/usr/lib/aliases	mail alias file
.SH SEE ALSO
aliases(5), delivermail(8)
