.TH PQ 1
.UC
.SH NAME
pq \- print quota
.SH SYNOPSIS
.B pq
[
.B \-
] [ directory ... ]
.SH DESCRIPTION
.I Pq
searches up the file system tree from the current directory
for the nearest quota node.
If it finds a quota node,
it prints the used and maximum quota
and the percentage of the quota which is currently used.
This is useful when you are several levels deep in your account and wish to
find out what your quota is.
.PP
If
a list of directories is specified,
.I pq
will look in those directories for quota nodes
and report on that.
.PP
If
.B \-
is given,
.I pq
will print the directory in which it found the quota,
even if only one
.I directory
is specified.
.SH SEE ALSO
du(1)
.SH AUTHOR
Kurt Shoens, Ken Arnold
.SH BUGS
.I Pq
should find the most restrictive quota in the tree,
or perhaps all relevant quotas,
and print that, perhaps with its name, ala
.IR pwd .
.PP
There are inherent problems with the implementation
of the quota system that can sometimes cause
quotas to be out of phase with reality.
