.TH RENICE 1
.UC
.SH NAME
renice \- oppress running processes
.SH SYNOPSIS
.B renice
newnice pid1
[
pid2 ...  pidn
]
.SH DESCRIPTION
.I Renice
will assign
.I pid1
, ...,
.I pidn
a ``niceness'' of
.IR newnice .
Positive niceness means a lower scheduling priority.
Negative niceness means a high priority.  The super-user may
renice any process to any value.  Other users may renice
their own processes to any value greater than the current value.
.SH SEE ALSO
nice(1), nice(2), renice(2)
