.TH STRIP 1 
.UC
.SH NAME
strip  \-  excise object program segments
.SH SYNOPSIS
.B strip
[
.B \-n
]
name ...
.SH DESCRIPTION
.I Strip
removes the symbol table and relocation bits ordinarily attached to the output
of the assembler and loader.
This is useful to save space after a program has been debugged.
.PP
The effect of
.I strip
is the same as use of the
.B \-s
option of
.IR ld .
.PP
The
.B \-n
flag removes a program's text, data, and relocation information segments,
leaving only the headers and symbol table.  This is useful for files such
as /unix, where only the symbol table information need be publicly readable.
.SH FILES
.ta 2i
/tmp/s??????	temporary files
.SH "SEE ALSO"
ld(1)
