.TH SROFF 1
.ad
.br
.SH NAME
sroff \- text formatting for Sanders printer
.SH SYNTAX
.B sroff
[ option ] ...
[ file ] ...
.SH DESCRIPTION
.I sroff
formats text in the named
.I files
for
printing on a Sanders Media 12/7 printer and
is similar to
.I nroff
and
.I troff,
from which it is derived.
The
.I Nroff/Troff user's manual
applies to
.I sroff
as well, with exceptions listed in the
.I Sroff Reference Manual.
In general,
.I sroff
works similarly to
.I troff,
although it has some of the limitations of
.I nroff.
.PP
If no
.I file
argument is present, the standard input is read.
An argument consisting of a single minus
.RB ( \- )
is taken to be
a file name corresponding to the standard input.
The options, which may appear in any order so long as they appear
before the files, are:
.TP "\w'\f3\-m\f1name 'u"
.BI \-o list
Print only pages whose page numbers appear in
the comma-separated
.I list
of numbers and ranges.
A range
.IB N - M
means pages
.I N
through
.IR M ;
an initial
.I -N
means
from the beginning to page
.IR N ;
and a final
.IR N \-
means
from
.I N
to the end.
.TP
.BI \-n N
Number first generated page
.IR N .
.TP
.BI \-m name
Use the macro package
.I name
by prepending the macro file
.BI /usr/lib/tmac/tmac. name
to the input
.IR files .
.TP
.BI \-r aN
Set register
.I a
(one-character) to
.IR N .
.TP
.B \-i
Read standard input after the input files are exhausted.
.TP
.B \-q
Invoke the simultaneous input-output mode of the
.B rd
request.
.TP
.BI \-F name
Mount set of fonts
.I name.
This option is dependent on the fonts mounted in the printer.
Examples are
.B H10
for Helvesan 10 point Regular and Italic and
.B M12
for Messenger 12 (underlining when in font 2).
.TP
.B \-d
Use draft mode, substituting fast-printing draft fonts whenever
available.
.TP
.B \-c
Set up for continuous (roll or fanfold) paper.
In particular, no top margin is generated by the printer.
.TP
.B \-nroff
Define
.B n
rather than
.B t
to emulate
.I nroff.
This can be useful for making macro packages work as with
.I nroff, especially when using a typewriter like font
or a set of fonts with no italics.
.TP
.B \-t
Direct output to the standard output instead
of the sanders printer.
.TP
.B \-w
Wait until printer is available, if
currently busy.
.TP
.B \-b
Report whether the printer
is busy or available.
No text processing is done.
.TP
.B \-z
Suppress output, just produce any diagnostic messages.
.TP
.B \-S
Notify the user when printing finishes.
Used when
.I sroff
is run in background.
.TP
.SH FILES
.ta \w'/usr/lib/tmac/tmac.*  'u
/tmp/ta*	temporary file
.br
/usr/lib/tmac/tmac.*	standard macro files
.br
/usr/lib/sfont/*	font width tables for
.I sroff
.br
/dev/sanders	printer
.SH "SEE ALSO"
.I Sroff Reference Manual
.br
J. F. Ossanna,
.I Nroff/Troff user's manual
.br
B. W. Kernighan,
.I
A TROFF Tutorial
.br
seqn(UA1), tbl(UA1)
