.TH CHOWN 8
.UC
.SH NAME
chown, chgrp \- change owner or group
.SH SYNOPSIS
.B chown
owner file ...
.PP
.B chown
owner.group file ...
.PP
.B chgrp
group file ...
.SH DESCRIPTION
.I Chown
changes the owner of the
.I files
to
.IR owner .
The owner may be either a decimal UID or
a login name found in the password file.
If the second form is given both the owner
and the group are changed.
.PP
.I Chgrp
changes the group-ID of the
.I files
to
.IR group .
The group may be either a decimal GID or
a group name found in the group-ID file.
.PP
Only the super-user can change owner or group,
in order to simplify as yet unimplemented accounting procedures.
.SH FILES
/etc/passwd
.br
/etc/group
.SH "SEE ALSO"
chown(2), group(5), passwd(5)
.SH "BUGS"
If the owner's name contains a '.', chown must be done with 
numeric user-id.
