.TH GETNAME 8
.UC
.SH NAME
getNAME \- get NAME sections from manual source for whatis/apropos data base
.SH SYNOPSIS
.B getNAME
[
.B \-t
]
name ...
.SH DESCRIPTION
.I Getname
reads the first few lines of each of the argument manual section sources,
and finds the \&.TH entry and the .SH entry writing them to the
standard output in a form suitable for making into the whatis/apropos
data base.
If the
.I \-t
option is used, the command name and a colon are prepended
to the output line, for use in making a table of contents.
.SH FILES
/usr/lib/whatis		Eventual data base
.SH "SEE ALSO"
apropos(1), makewhatis(8), whatis(1)
