.TH MAKEWHATIS 8
.UC
.SH NAME
makewhatis \- remake the data base for the whatis and apropos commands
.SH SYNOPSIS
.B makewhatis
.SH DESCRIPTION
.I Makewhatis
remakes the data base for the
whatis and apropos commands
from the manual sections in /usr/man/*.
It uses
.IR getNAME (8)
to extract relevant text from each manual entry
and then rearranges and sorts this output.
Manuals sections may be in either the old (version 6) or version 7 manual
formats.
.SH FILES
.DT
/usr/lib/whatis		constructed data base
.SH SEE ALSO
getNAME(8)
