.\" Copyright (c) 1983 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
.\"
.\"	@(#)newfs.8	6.3 (Berkeley) 5/21/86
.\"
.TH NEWFS 8 "May 21, 1986"
.UC 5
.SH NAME
newfs \- construct a new file system
.SH SYNOPSIS
.B /etc/newfs
[
.B \-N
]
.B special disk-type cpu-type
.SH DESCRIPTION
.I Newfs
is a ``friendly'' front-end to the
.IR mkfs (8)
program.
.I Newfs
will look up the type of disk a file system is
being created on in the disk description
file
.IR /etc/disktab ,
calculate the appropriate
parameters to use in calling
.IR mkfs ,
then build the file system by forking \fImkfs\fP.
The
.B \-N
option causes the file system parameters to be printed out
without actually creating the file system.
.PP
\fINewfs\fP without arguments will print a list of the disk and cpu
types that it is familiar with.
.PP
.SH FILES
/etc/disktab	for disk geometry and file system partition information 
.br
/etc/mkfs	to actually build the file system
.SH "SEE ALSO"
disktab(5), fs(5), diskpart(8), fsck(8), format(8), mkfs(8), tunefs(8)
.SH BUGS
Should figure out the disk and cpu types without the user's help.
.PP
The standard 4.3BSD C libarary disktab structure, as declared in
\fI/usr/include/disktab.h\fP, was not sufficient to convey the
information the PDP-11 needs, such as the relationship between the cpu
type and the M/N values.  Therefore, the relevant values were
extracted from the \fI/etc/disktab\fP file and hardwired into the
\fInewfs\fP program.  If you have an unknown disk or cpu type, you
may want to read through \fI/etc/disktab\fP and \fInewfs\fP to find
a similar disk or cpu.
