: '@(#)news.install	1.3 5/9/81'
if test "$#" != 3
then
	echo "usage: $0 newsdir nuser ngroup"
	exit 1
fi
NEWSDIR=$1
NEWSUSR=$2
NEWSGRP=$3


: Get name of local system
SYSNAME=`grep sysname /usr/include/whoami.h | sed 's/.*\"\(.*\)\".*/\1/'`
if test "$SYSNAME" = ""
then
	echo "$0: Cannot get system name"
	exit 1
fi

: Ensure NEWSDIR exists
if test ! -d $NEWSDIR
then
	mkdir $NEWSDIR
fi
chmod 755 $NEWSDIR
chown $NEWSUSR $NEWSDIR
chgrp $NEWSGRP $NEWSDIR

: Ensure certain files in NEWSDIR exist
touch $NEWSDIR/.uindex $NEWSDIR/.nindex $NEWSDIR/.history $NEWSDIR/.bitfile

: If no .sys file, make one.
if test ! -f $NEWSDIR/.sys
then
echo making a .sys file to link you to ucbvax
	cat > $NEWSDIR/.sys << EOF
$SYSNAME:NET.ALL,to_$SYSNAME
ucbvax:NET.ALL,to_ucbvax
EOF
fi

: If no .seq file, make one.
if test ! -f $NEWSDIR/.seq
then
	echo '100' >$NEWSDIR/.seq
fi

: If no .ngfile, make one.
if test ! -f $NEWSDIR/.ngfile
then
	cat > $NEWSDIR/.ngfile << EOF
ALL
general
fa.arms-d
fa.arpa-bboard
fa.energy
fa.human-nets
fa.info-cpm
fa.info-micro
fa.info-terms
fa.sf-lovers
fa.unix-wizards
net.4bsd-bugs
net.4bsd-patches
net.arpa-uucp
net.csfrp
net.general
net.news
net.periphs
net.sources
net.v7bugs
test
to_duke
to_ucbvax
to_$SYSNAME
EOF
fi

: ensure index files are in most recent first order
sort -t: -rn +1 $NEWSDIR/.nindex -o $NEWSDIR/.nindex
sort -t: -rn +1 $NEWSDIR/.uindex -o $NEWSDIR/.uindex

chmod 644 $NEWSDIR/.[a-z]*
chown $NEWSUSR $NEWSDIR/.[a-z]*
chgrp $NEWSGRP $NEWSDIR/.[a-z]*

if test -d $NEWSDIR/.canned
then
	chmod 755 $NEWSDIR/.canned
fi

echo reminder: uux must permit rnews if running over uucp
