#define	cx_beginbuf	CxBgnBf
#define	cx_beginfile	CxBgnFl
#define	gen_clreol	GnClEol
#define	gen_clreos	GnClEos
#define	gen_delchar	GnDChar
#define	gen_delline	GnDLine
#define	gen_setinsert	GnSIns
#define	gen_setmodes	GnSMds
#define	h19_clreol	H19CEol
#define	h19_clreos	H19CEos
#define	h19_delchar	H19DChr
#define	h19_delline	H19DLin
#define	h19_setinsert	H19SIns
#define	h19_setmodes	H19SMds
#define	p_expr11	PExpr11
#define	p_expr12	PExpr12
#define	p_statement	PStmnt
#define	p_statementlist	PStmntL
#define	s_gettok	SGetTk
#define	s_gettok1	SGetTk1
#define	tt_clreol	TtClEol
#define	tt_clreos	TtClEos
#define	var_set1	VrSet1
#define	var_setnum1	VrSNum1
#define	var_setstr1	VrSStr1
#define	wwclreol1	WwClEl1
#define	wwclreos	WwClEs1
#define	wwcursorcol	WwCrCol
#define	wwcursormodes	WwCrMds
#define	wwcursorrow	WwCrRow
#define	wwdelete	WwDel
#define	wwdelete1	WwDel1
#define	wwdumpns	WwDmpNS
#define	wwdumpnvis	WwDmpNV
#define	wwframe		WwFrm
#define	wwframec	WwFrmC
#define	wwnread		WwNRd
#define	wwnreadc	WwNRdC
#define	wwnreade	WwNRdE
#define	wwnreadz	WwNRdZ
#define	wwnselect	WwNSel
#define	wwnselecte	WwNSelE
#define	wwnselectz	WwNSelZ
#define	wwnwread	WwNWRd
#define	wwnwreadc	WwNWRdC
#define	wwnwreadd	WwNWRdD
#define	wwnwreade	WwNWRdE
#define	wwnwreadp	WwNWRdP
#define	wwnwreadz	WwNWRdZ
#define	wwredraw	WwRdw
#define	wwredrawwin1	WwRdwW1
#define	wwscroll	WwScrl
#define	wwscroll1	WwScrl1
