.\" Copyright (c) 1980 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
.\"
.\"	@(#)mklost+found.8	6.1 (Berkeley) 8/13/87
.\"
.TH MKLOST+FOUND 8 "August 13, 1987"
.UC 4
.SH NAME
mklost \- make a lost+found directory for fsck
.SH SYNOPSIS
.B /etc/mklost
.SH DESCRIPTION
A directory
.I lost+found
is created in the current directory and a number of empty files
are created therein and then removed so that there will be
empty slots for
.IR fsck (8).
This command should be used whenever a new file system is created with
.IR mkfs (8)
or
.IR newfs (8).
.SH "SEE ALSO"
fsck(8),
mkfs(8)
