.\" Copyright (c) 1983 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
.\"
.\"	@(#)newfs.8	7.0 (Berkeley) 12/28/91
.\"
.TH NEWFS 8 "December 28, 1991"
.UC 5
.SH NAME
newfs \- construct a new file system
.SH SYNOPSIS
.B /etc/newfs
[
.B \-N
]
[
.B \-m free-gap
]
[
.B \-b
]
[
.B \-B bootblock
]
.B special disk-type
.SH DESCRIPTION
.I Newfs
is a ``friendly'' front-end to the
.IR mkfs (8)
program.
.I Newfs
will look up the type of disk a file system is
being created on in the disk description
file
.IR /etc/disktab ,
calculate the appropriate
parameters to use in calling
.IR mkfs ,
then build the file system by forking \fImkfs\fP.
.PP
The
.I \-N
option causes the file system parameters to be printed out
without actually creating the file system.
.PP
The
.I \-m
option allows the specification of the block interleaving of the free list
(the
.I m
parameter of 
.IR mkfs ).
If not specified or outside the range 0 thru 31 then 
.I m
is given a value of 2.
The 
.I n
parameter to 
.I mkfs
is calcuated by
.I newfs
to be 1 cylinder in size.
.PP
The
.IR \-b 
and
.IR \-B
options specify that a primary block zero bootstrap should be installed in
block zero of
.IR special .
This is typically done for `a' partitions to make disks bootable.
If
.I \-b
is specified,
.I newfs
will attempt to use a default boot block (defined in
.IR /etc/disktab ).
.PP
The
.I \-B
option allows one to specify the file to read the boot block from
.RI ( bootblock ).
Note that a boot block can always be copied separately via:
.PP
	\fBdd if=\fIbootblock\fB of=\fIspecial\fB bs=512 count=1 conv=sync\fR
.PP
.SH FILES
/etc/disktab	for disk geometry and file system partition information 
.br
/etc/mkfs	to actually build the file system
.br
/mdec/*	block zero bootstraps
.SH "SEE ALSO"
disktab(5), fs(5), diskpart(8), fsck(8), format(8), mkfs(8)
.SH BUGS
