.\" Copyright (c) 1980 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
.\"
.\"	@(#)reboot.8	6.5 (Berkeley) 9/6/88
.\"
.TH REBOOT 8 "September 6, 1988"
.UC 2
.SH NAME
reboot \- UNIX bootstrapping procedures
.SH SYNOPSIS
.B /etc/reboot
[
.B \-lqnhdarsf
]
.br
.B /etc/halt
[
.B \-lqndars
]
.br
.B /etc/fastboot
[
.B \-lqndars
]
.SH DESCRIPTION
.PP
UNIX is started by placing it in memory at location zero and transferring to
its entry point.  Since the system is not reentrant, it is necessary to read
it in from disk or tape each time it is to be boot strapped.
.PP
.B "Rebooting a running system:"
When UNIX is running and a reboot is desired,
.IR shutdown (8)
is normally used to stop time sharing and put the system into single user
mode.  If there are no users then
.B /etc/reboot
can be used without shutting the system down first.
.PP
Reboot normally causes the disks to be synced and allows the system to
perform other shutdown activities such as resynchronizing hardware
time-of-day clocks.  A multi-user reboot (as described below) is then
initiated.  This causes a system to be booted and an automatic disk check
to be performed.  If all this succeeds without incident, the system is then
brought up for multi-user operation.
.PP
Options to reboot are:
.TP
.B \-l
Don't try to tell
.IR syslogd (8)
what's about to happen.
.TP
.B \-q
Reboot quickly and ungracefully, without shutting down running processes
first.
.TP
.B \-n
Don't sync before rebooting.  This can be used if a disk or the processor
is on fire.
.TP
.B \-h
Don't reboot, simply halt the processor.
.TP
.B \-d
Dump memory onto the dump device, usually part of swap, before rebooting.
The dump is done in the same way as after a panic.
.TP
.B \-a
Have the system booter ask for the name of the system to be booted, rather
than immediately booting the default system.
.TP
.B \-r
Mount the root file system as
.I "read only"
when the system reboots.
.TP
.B \-s
Don't enter multi-user mode after system has rebooted \- stay in single
user mode.
.TP
.B \-f
Fast reboot.  Omit the automatic file system consistency check when the system
reboots and goes multi-user.  This is accomplished by passing a
.I fast reboot
flag on to the rebooting kernel.  This currently prevents the use of
.B \-f
flag in conjunction with the
.B \-h
(halt) flag.
.PP
.I Reboot
normally places a shutdown record in the login accounting file
/usr/adm/wtmp.  This is inhibited if the
.B \-q
or
.B \-n
options are present.
Note that the
.B \-f
(fast reboot) and
.B \-n
(don't sync)
options are contradictory; the request for a fast reboot is ignored in this
case.
.PP
.I Halt
and
.I fastboot
are synonymous with ``\fBreboot \-h\fP'' and ``\fBreboot \-f\fP'', respectively.
.PP
.B "Power fail and crash recovery:"
Normally, the system will reboot itself at power-up or after crashes
(if the contents of low memory are intact.)
An automatic consistency check of the file systems will be
performed, and unless this fails, the system will resume multi-user
operations.
.PP
.B "Cold starts:"
A PDP-11 UNIX system is started by a two-stage process.  The first is a
primary bootstrap which is able to read in relatively small stand-alone
programs; the second (called
.IR boot )
is used to read in the system itself.
.PP
The primary bootstrap must reside in the otherwise unused block zero of the
boot device.  It can be read in and started by standard ROM cold boot
routines or, if necessary, by keying in a small startup routine.  The
primary bootstrap is capable of loading type 0407 executable files (impure
(non-shared), non-separate I&D.)
Copies of the block zero bootstraps are kept in the directory
.IR /mdec .
.IR Newfs (8)
will normally place a copy of the appropriate bootstrap in block zero of
new file systems.
.PP
The primary bootstrap will normally load
.I boot
from the file system that starts at block 0 of drive 0 of the boot device
(this is usually root.)
If
.I boot
is not found, the name of another file to try will be read from the
console.  Some devices' primary bootstraps, when asking for alternate
programs to boot, will prompt with a `>', others have no prompt because of
space considerations (and some, like the RA boot, can't even ask for
alternate program names.)  No diagnostic message results if the file cannot
be found, and no provision is made for correcting typographical errors when
entering alternate names.  Hitting a return will cause an error and allow
restarting.
.IP \(bu
.BR "In an emergency" ,
the bootstrap methods described in the paper
.I "Installing and Operating 2.10bsd"
can be used to boot from a distribution tape.
.PP
The secondary boot step, called
.IR boot ,
actually brings in the system.  When read into location 0 and executed,
.I boot
sets up memory management, relocates itself into high memory, and types its
name and a `:' on the console.  If this is an automatic, unattended reboot,
.I boot
will use a default file specification for the installation, typing the
file's name after the prompt.  Otherwise, it reads a file specification
from the console.  Normal line editing characters can be used to make
corrections while typing this (see below for file specification format.)
If only a carriage return is typed, a default name will be used.
.I Boot
finds the [specified] file and loads it into memory location zero, sets up
memory management as required, and calls the program by executing a `trap'
instruction.
.PP
Conventionally, the secondary boot program is `/boot' (if the root is the
first file system on disk 0 of the boot device) and the name of the current
version of the system is `/unix'.
.PP
For the system to boot,
.I /etc/init
must exist and be executable; if it is not, the kernel will print a message
to that effect and loop.  Further, for a single user boot, the files
.I /bin/sh
and
.I /dev/console
must also exist and
.I /bin/sh
must be executable (if either of these is missing,
.I init
will attempt multi-user operation.)
For a multi-user boot the file
.I /etc/ttys
must exist (if missing,
.I init
will attempt single user operation.)
.PP
When the system is running in single user mode, it starts a single user
shell on the console which types a `#' prompt.  After doing any file system
checks and setting the date
.RI ( date (1))
a multi-user system can be brought up by typing an EOT (control-d) in
response to the `#' prompt.
.PP
.B "Boot file specification format:"
The file specifications used with
.I boot
are of the form:
.IP
.I device(unit,offset)path
.LP
where
.I device
is the type of the device to be searched;
.I unit
is the unit number of the disk or tape;
.I offset
is the block offset of a UNIX file system on the specified disk,
in physical (512 byte) blocks,
or the tape file number if the device is a tape; and
.I path
is the path name of a disk file to be loaded with all mount prefixes
stripped off
.RI ( path
should be omitted for tape files.)  Tape files are separated by single tape
marks.
.I Device
is one of the following
.PP
.nf
.ne 10
	xp	RM02/03/05, RP04/05/06, DIVA, SI Eagle, CDC 9766, Fuji 160
	rp	RP03
	rk	RK05
	hk	RK06/7
	rl	RL01/2
	si	RM05, CDC 9766
	ra	RA60/80/81, RX50, RD51/52/53, RC25
	ht	TU/TE16
	tm	TU/TE10
	ts	TS-11
.fi
.PP
The stand alone tape drive unit number is specially encoded to specify
both unit number and tape density (BPI).  Most tape subsystems either
automatically adjust to tape density or have switches on the drives to
force the density to a particular setting, but for those which don't the
following density select mechanisms may be necessary.  The \fBts\fP only
operates at 1600BPI, so there is no special unit density encoding.  The
\fBht\fP will operate at either 800BPI or 1600BPI.  Units 0 through 3
correspond to 800BPI, and 4 through 7 to 1600BPI on drives 0 through 3
respectively.  The standard DEC \fBtm\fP only supports 800BPI (and hence
can't be used with the standard \*(2B distribution tape), but several
widely used \fBtm\fP emulators support 1600BPI and even 6250BPI.  Units 0
through 3 correspond to 800BPI, 4 through 7 to 1600BPI, and 8 through 11
to 6250BPI on drives 0 through 3 respectively.
.PP
For example, to boot a system which starts at block 0 of unit 0 on an RK07,
type \*(lqhk(0,0)unix\*(rq to the boot prompt.  The specification
\*(lqra(0,9700)unix\*(rq indicates an MSCP disk, unit 0, and the file
system found starting at block 9700 which would be appropriate for
partition `b' of an RD51, '52, or '53.  And the specification
\*(lqts(0,3)\*(rq would cause the fourth file on a tape threaded on `ts'
tape drive 0 to be loaded and executed.
.PP
.B "Cold boot loaders:"
The following programs to load and execute the primary bootstrap may be
installed in read-only memories or manually keyed into main memory.  Each
program is position-independent but should be placed well above location 0
so it will not be overwritten.  Each reads a block from the beginning of a
device into core location zero.  The octal words constituting the program
are listed on the left.
.PP
.nf
.if n .ta 3 11 15 23 38
.if t .ta .3i 1i 1.4i 2i 3.5i
.ne 10
RK (drive 0):
	012700		mov	$rkda,r0
	177412
	005040		clr	\-(r0)	/ rkda cleared by start
	010040		mov	r0,\-(r0)
	012740		mov	$5,\-(r0)
	000005
	105710	1:	tstb	(r0)
	002376		bge	1b
	005007		clr	pc
.PP
.ne 11
RP (drive 0)
	012700		mov	$rpmr,r0
	176726
	005040		clr	\-(r0)
	005040		clr	\-(r0)
	005040		clr	\-(r0)
	010040		mov	r0,\-(r0)
	012740		mov	$5,\-(r0)
	000005
	105710	1:	tstb	(r0)
	002376		bge	1b
	005007		clr	pc
.PP
.ne 7
TM and TS (drive 0):
	012700		mov	$tmba,r0
	172526
	010040		mov	r0,\-(r0)
	012740		mov	$60003,\-(r0)
	060003
	000777		br	.
.DT
.SH FILES
.ta \w'/mdec/xxuboot   'u
/unix	system code
.br
/boot	system bootstrap
.br
/etc/init	system process dispatcher
.br
/mdec/xxuboot	sector 0 boot blocks, xx is disk type
.SH "SEE ALSO"
crash(8V),
fsck(8),
init(8),
newfs(8),
rc(8),
shutdown(8),
syslogd(8)
