#define ERR_READING_LEN AERR_READING_LEN
#define GetHostDomain	BGetHostDomain
#define GetHostInfo	AGetHostInfo
#define LookupHost	ALookupHost
#define Print_cdname	APrint_cdname
#define	Print_cdname_sub BPrint_cdname_sub
#define StringToType	AStringToType
#define curHostInfo	AcurHostInfo
#define defaultAddr	DdefaultAddr
#define defaultName	AdefaultName
#define defaultPtr	BdefaultPtr
#define defaultServer	CdefaultServer
#define host_aliases	Ahost_aliases
#define res_skip	Ares_skip
