.TH ABORT 3
.SH NAME
abort \- generate IOT fault
.SH SYNTAX
.B abort()
.SH DESCRIPTION
.I Abort
executes the PDP-11 IOT instruction.
This causes a signal that normally terminates
the process with a core dump, which may be used for debugging.
.SH SEE ALSO
adb(1), exit(2), signal(2)
.SH DIAGNOSTICS
Usually `IOT trap \- core dumped' from the shell.
