.TH LOADAV 3 
.UC
.SH NAME
loadav \- get load average
.SH SYNOPSIS
.B loadav(vec)
.br
.B double vec[3];
.SH DESCRIPTION
.I Loadav
returns the load average on the system.
The three numbers returned are the 1, 5, and 15 minute load averages.
A load average is the average length of the run queue over the
indicated period of time.
It suggests what fraction of the CPU you would get for a CPU bound process.
For example, a load of 3.00 indicates you would get 1/3 of the CPU.
The higher the load, the more loaded the system.
The different numbers can be used to give some indication of whether the
load is going up or down.
.SH "SEE ALSO"
la(1), w(1), gldav(2)
.SH BUGS
Only measures the load on the CPU.
If the system is I/O bound,
it won't indicate the true load.
