#	%M%	%I%	%E%
#
CFLAGS=	-O -w -DVFORK
LFLAGS=
LIBS=	-lm -lc
DESTDIR=
LIBDIR=	/usr/new/lib/apl
LD=	ld
ALL=	xed apl aplcvt cata

OBJ1 = a0.o a1.o a3.o a4.o a5.o a6.o a7.o a8.o a9.o 
OBJ2 = aa.o ab.o ac.o ad.o ae.o af.o ag.o ah.o ai.o aj.o 
OBJ3 = ak.o al.o an.o ao.o aq.o at.o aw.o ax.o ay.o az.o
OBJ4 = y.tab.o a2.o am.o
XEDOBJ = xed.o
CVTOBJ = aplcvt.o
CATOBJ = cata.o

all:	${ALL}

apl:	$(OBJ1) $(OBJ2) $(OBJ3) $(OBJ4)
	$(LD) $(LFLAGS) /lib/crt0.o -o apl \
		$(OBJ1) $(OBJ2) $(OBJ3) $(OBJ4) $(LIBS)


$(OBJ1) $(OBJ2) $(OBJ3): apl.h

a0.o:	a0.c
	${CC} -c ${CFLAGS} -DLIBDIR=\"${LIBDIR}\" a0.c

a2.o:	a2.c apl.h aplmap.h

am.o:	am.c apl.h

y.tab.o: y.tab.c lex.c tab.c apl.h

y.tab.c: apl.y
	$(YACC) apl.y

rebuild:
	$(YACC) apl.y
	$(CC) $(CFLAGS) -c a?.c y.tab.c
	$(LD) $(LFLAGS) /lib/crt0.o -o apl *.o $(LIBS)
	: APL rebuild complete

xed:
	cc ${CFLAGS} -o xed xed.c

aplcvt:
	cc ${CFLAGS} -o aplcvt aplcvt.c

cata:
	cc ${CFLAGS} -o cata cata.c

cp:	apl aplcvt xed cata
	chmod 755 xed aplcvt cata
	chmod 644 xed.doc
	cp xed ${DESTDIR}/usr/new ; strip ${DESTDIR}/usr/new/xed
	cp aplcvt ${DESTDIR}/usr/new ; strip ${DESTDIR}/usr/new/aplcvt
	cp cata ${DESTDIR}/usr/new ; strip ${DESTDIR}/usr/new/cata
	cp apl ${DESTDIR}/usr/new ; strip ${DESTDIR}/usr/new/apl

clean:
	rm -f $(OBJ1) $(OBJ2) $(OBJ3) $(OBJ4) $(XEDOBJ) $(CVTOBJ) $(CATOBJ)
	rm -f xed apl aplcvt cata

apl2:	FRC
	rm -f *.o y.tab.c
	$(YACC) apl.y
	$(CC) $(CFLAGS) -DAPL2 -c a?.c y.tab.c
	$(LD) $(LFLAGS) /lib/crt0.o -o apl2 *.o $(LIBS)
	rm -f *.o y.tab.c
	: APL2 build complete

FRC:
