.\" Copyright (c) 1980 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
.\"
.\"	@(#)xp.4	6.3 (2.11BSD GTE) 12/30/92
.\"
.TH XP 4 "September 7, 1988"
.UC 2
.SH NAME
xp \- generic SMD moving-head disk
.SH SYNOPSIS
.ft B
.nf
/sys/conf/SYSTEM:
.ta .5i +\w'XP_PROBE 'u +\w'xp_controllers 'u
	# Because the disk drive type registers conflict with other DEC
	# controllers, you cannot use XP_PROBE for the Ampex 9300 and
	# Diva drives.  Read through /sys/pdpuba/hpreg.h and /sys/pdpuba/xp.c
	# for information on how to initialize for these drives.
	NXPC	\fIxp_controllers\fP	# NXPD controllers (RH70/RH11 style)
	NXPD	\fIxp_drives\fP	# RM02/03/05, RP04/05/06, CDC 9766,
					# Ampex 9300, Diva, Fuji 160, SI Eagle.
	XP_PROBE	\fIYES\fP	# check drive types at boot
.DT

/etc/dtab:
.ta .5i +\w'#Name 'u +\w'Unit# 'u +\w'177777 'u +\w'Vector 'u +\w'Br 'u +\w'xxxxxxx 'u +\w'xxxxxxx 'u
	#Name	Unit#	Addr	Vector	Br	Handler(s)		# Comments
	xp	?	176700	254	5	xpintr		# xp driver
.DT

major device number(s):
	raw: 19
	block: 10
minor device encoding:
	bits 0007 specify partition of XP drive
	bits 0070 specify XP drive
.fi
.ft R
.SH DESCRIPTION
The
.I xp
driver is a generic SMD storage module disk driver.  It can be adapted to
most SMD controllers (although bootstrapping will not necessarily be
directly possible.)  The drives are numbered from 0 to
.I n
on
controller 0, from
.IR n +1
to
.I m
on controller 1, etc.  The drives may have different geometries.
.PP
Files with minor device numbers 0 through 7 refer to various portions
of drive 0;
minor devices 8 through 15 refer to drive 1, etc.
The standard device names begin with ``xp'' followed by
the drive number and then a letter a-h for partitions 0-7 respectively.
The character ? stands here for a drive number in the range 0-7.
.PP
The block files access the disk via the system's normal
buffering mechanism and may be read and written without regard to
physical disk records.  There is also a `raw' interface
which provides for direct transmission between the disk
and the user's read or write buffer.
A single read or write call results in exactly one I/O operation
and therefore raw I/O is considerably more efficient when
many words are transmitted.  The names of the raw files
conventionally begin with an extra `r.'
.PP
In raw I/O the buffer must begin on a word (even) boundary,
and counts should be a multiple of 512 bytes (a disk sector).
Likewise
.I seek
calls should specify a multiple of 512 bytes.
.SH "DISK SUPPORT"
If the option
.B XP_PROBE
is selected the driver interrogates the controller's drive type register
to determine the type of drive attached.  The driver recognizes the
following drives automatically:  RM02/03/05 (the CDC 9766 is recognized
as an RM05), SI 9775, RP04/05/06, Fuji 160, Capricorn and SI Eagle.  The
following drives are also supported, but must either be patched at boot
time or initialized at compile time: Ampex 9300 in direct mode and DIVA
Comp V.
.PP
The origin and size (in sectors) of the pseudo-disks on each drive are as
follows:
.nf
.ta .5i +\w'disk  'u +\w'0000000  'u +\w'0000000  'u +\w'000 - 0000  'u
.PP
.ne 10
RP04/05 partitions:
	disk	 start	 length	      cyls	comments
	xp?a	     0	   9614	  0 -   22	/
	xp?b	  9614	   8778	 23 -   43	swap
	xp?c	 18392	 153406	 44 -  410*	/usr
	xp?d	unusable
	xp?e	unusable
	xp?f	unused
	xp?g	     0	 171798	  0 -  410*	whole pack
	xp?h	unusable
.PP
.ne 10
RP06 partitions:
	disk	 start	 length	      cyls	comments
	xp?a	     0	   9614	  0 -   22	/
	xp?b	  9614	   8778	 23 -   43	swap
	xp?c	 18392	 153406	 44 -  410	/usr
	xp?d	171798	 168872	411 -  814*
	xp?e	 18392	 322278	 44 -  814*	
	xp?f	unused
	xp?g	     0	 171798	  0 -  410
	xp?h	     0	 340670	  0 -  814*	whole pack
.PP
.ne 10
RM02/RM03 partitions:
	disk	 start	 length	      cyls	comments
	xp?a	     0	   9600	  0 -   59	/
	xp?b	  9600	   9600	 60 -  119	swap
	xp?c	     0	 131680	  0 -  822*	whole pack + bad144 track
	xp?d	unused
	xp?e	unused
	xp?f	unused
	xp?g	 19200	 112320	120 -  821
	xp?h         0	 131520   0 -  821	whole pack - bad144 track
.PP
.ne 10
RM05 (or SI 9500, CDC 9766) partitions:
	disk	 start	 length	      cyls	comments
	xp?a	     0	   9120	  0 -   14	/
	xp?b	  9120	   9120	 15 -   29	swap
	xp?c	 18240	 234080	 30 -  414
	xp?d	252320	 248064	415 -  822*
	xp?e	 18240	 164160	 30 -  299	/usr
	xp?f	182400	 152000	300 -  549
	xp?g	334400	 165984	550 -  822*
	xp?h	     0	 500384	  0 -  822*	whole pack
.PP
.ne 10
Capricorn partitions:
	disk	 start	 length	      cyls	comments
	xp?a	     0	  16384	  0 -   31	/
	xp?b	 16384	  33792	 32 -   97	swap
	xp?c	 50176	 291840	 98 -  667	/usr
	xp?d	342016	  16384	668 -  699
	xp?e	358400	  56320	700 -  809
	xp?f	414720	 109568	810 - 1023*
	xp?g	342016	 182272	668 - 1023*
	xp?h	     0	 524288	  0 - 1023*	whole pack
.PP
.ne 10
SI, CDC 9775 (direct) partitions:
	disk	 start	 length	      cyls	comments
	xp?a	     0	  10240	  0 -    7	/
	xp?b	 10240	  10240	  8 -   15	swap
	xp?c	 20480	 510720	 16 -  414
	xp?d	531200	 547840	415 -  842*
	xp?e	 20480	 363520	 16 -  299	/usr
	xp?f	384000	 320000	300 -  549
	xp?g	704000	 375040	550 -  842*
	xp?h	     0	1079040	  0 -  842*	whole pack
.PP
.ne 10
SI 6100, Fuji Eagle 2351A partitions:
	disk	 start	 length	      cyls	comments
	xp?a	     0	  11520	  0 -   11	/
	xp?b	  9600	  11520	 12 -   23	swap
	xp?c	 19200	 474240	 24 -  517
	xp?d	 19200	  92160	518 -  613	/usr
	xp?e	144640	 218880	614 -  841*
	xp?f	unused
	xp?g	unused
	xp?h	     0	 808320	  0 -  841*	whole pack
.PP
.ne 10
Emulex SC01B or SI 9400, Fuji 160 partitions:
	disk	 start	 length	      cyls	comments
	xp?a	     0	   9600	  0 -   29	/
	xp?b	  9600	   9600	 30 -   59	swap
	xp?c	 19200	 244160	 60 -  822*
	xp?d	 19200	 125440	 60 -  451	/usr
	xp?e	144640	 118720	452 -  822*
	xp?f	144640	  59520	452 -  637
	xp?g	204160	  59200	638 -  822*
	xp?h	     0	 263360	  0 -  822*	whole pack
.PP
.ne 10
Diva Comp V, Ampex 9300 partitions:
	disk	 start	 length	      cyls	comments
	xp?a	     0	   9405	  0 -   14	/
	xp?b	  9405	   9405	 15 -   29	swap
	xp?c	 18810	 241395	 30 -  414
	xp?d	260205	 250800	415 -  814*
	xp?e	 18810	 169290	 30 -  299	/usr
	xp?f	188100	 156750	300 -  549
	xp?g	313500	 166155	550 -  814*
	xp?h	     0	 511005	  0 -  814*	whole pack
.DT
.fi
.PP
Those partitions marked with an asterisk (``*'') allow access to bad block
information stored at the end of some packs.  Extreme care must be taken when
creating file systems on these partitions to avoid overwriting any bad block
information present.  In general it's best to use
.IR newfs (8)
to create file systems since it uses the ``safe'' partition sizes recored in
.IR /etc/disktab .
.PP
Special files should only be created for the
partitions that are actually used,
as the overlap in these addresses could lead to confusion otherwise.
The xp?a partition is normally used for the root file system,
the xp?b partition as a swap area,
and the xp?h partition for pack-pack copying (it maps the entire disk).
.SH FILES
.ta \w'/dev/MAKEDEV.local  'u
/dev/xp[0-7][a-h]	block files
.br
/dev/rxp[0-7][a-h]	raw files
.br
/dev/MAKEDEV	script to create special files
.br
/dev/MAKEDEV.local	script to localize special files
.SH SEE ALSO
hk(4),
ra(4),
ram(4),
rk(4),
rl(4),
rp(4),
rx(4),
si(4),
dtab(5),
autoconfig(8),
newfs(8)
.SH DIAGNOSTICS
\fBxp%d%c: hard error sn%d cs2=%b er1=%b\fR.  An unrecoverable
error occurred during transfer of the specified sector of the specified
disk partition.  The contents of the two error registers are also printed
in octal and symbolically with bits decoded.
The error was either unrecoverable, or a large number of retry attempts
(including offset positioning and drive recalibration) could not
recover the error.
.PP
\fBxp%d: write locked\fR.  The write protect switch was set on the drive
when a write was attempted.  The write operation is not recoverable.
.PP
\fBxp%d%c: soft ecc sn%d\fR.  A recoverable ECC error occurred on the
specified sector of the specified disk partition.  This happens normally
a few times a week.  If it happens more frequently than
this the sectors where the errors are occurring should be checked to see
if certain cylinders on the pack, spots on the carriage of the drive
or heads are indicated.
.PP
\fBxp%d: unknown device type 0%o\fR.  The number in the drive's drive
type register is unknown to the xp driver.
.SH BUGS
In raw I/O
.I read
and
.IR write (2)
truncate file offsets to 512-byte block boundaries,
and
.I write
scribbles on the tail of incomplete blocks.
Thus,
in programs that are likely to access raw devices,
.I read, write
and
.IR lseek (2)
should always deal in 512-byte multiples.
.PP
DEC-standard error logging should be supported.
.PP
The partition tables for the file systems should be read off of each
pack, as they are never quite what any single installation would prefer,
and this would make packs more portable.
.PP
If the drive types and parameters are not initialized, the
.I xp
driver uses drive type registers to discern the type of disk attached
to each drive.  Because of numbering conflicts, foreign disks and/or
controllers frequently cause this automatic recognition scheme to fail.
