# This is a special case for creating 1600bpi distributions on a TU81
# (the various binary images must obviously be the pdp-11 ones).
# TU81s do not handle the open/write/close/open/write/etc cycle,
# apparently a lingering serious exception is left (possibly because
# of density switching) when a close at low density is done.  'maketape'
# (the dd and tar commands as well) would receive hard errors after the
# first record/file.

# The solution was three fold: 
#	1) 'maketape' was modified to write tapemarks rather than
#	   doing close/open.
#	2) temporary files are constructed by tar (a large empty partition
#	   is necessary for all this to work)
#	3) a version of maketape.data is constructed on the fly with
#	   the extra files appended to it - this allows 'maketape'
#	   to write the entire tape without closing.

# TAPE	which tape to write the distribution on
# DUMP	where to store a root system dump if you do a ``make dump''
#
TAPE=	mt0
DUMP=	/xusr/root.dump
TMP1=	/xusr/1st.tar
TMP2=	/xusr/2nd.tar

ROOT=	/xusr/root

distribution: tape1 switch_tapes tape2

tape1: ${TMP2} ${TMP1}
	./maketape /dev/r${TAPE} maketape.data

switch_tapes: FRC
	@echo "Switch tapes.  Hit CR when second tape is mounted."
	@echo "DON'T FORGET TO CLEAN UP THE TAR TEMP FILES WHEN DONE!"
	@head -1

FRC:

tape2:
	cd ${ROOT}/usr/src; tar cfb /dev/r${TAPE} 20 \
		Makefile asm.sed asm.sed.pdp asm.sed.vax bin etc games \
		lib local man new old ucb usr.bin usr.lib

${TMP1}:
	cd ${ROOT}/usr; tar cf ${TMP1} \
		adm bin dict doc games guest hosts include ingres lib \
		local man msgs new old preserve pub skel spool tmp ucb

${TMP2}:
	cd ${ROOT}/usr/src; tar cf ${TMP2} sys include
