#
# usr.bin makefile
#

CFLAGS=	-O

512dumpdir: 512dumpdir.o
	${CC} ${LFLAG} $@.o -o $@

at: at.o
	${CC} ${LFLAG} $@.o -o $@

basename: basename.o
	${CC} ${LFLAG} $@.o -o $@

cal: cal.o
	${CC} ${LFLAG} $@.o -o $@

cb: cb.o
	${CC} ${LFLAG} $@.o -o $@

checkeq: checkeq.o
	${CC} ${LFLAG} $@.o -o $@

checkobj: checkobj.o
	${CC} ${LFLAG} $@.o -o $@

col: col.o
	${CC} ${LFLAG} $@.o -o $@

comm: comm.o
	${CC} ${LFLAG} $@.o -o $@

crypt: crypt.o
	${CC} ${LFLAG} $@.o -o $@

cu: cu.o
	${CC} ${LFLAG} $@.o -o $@

cu.3451A: cu.3451A.o
	${CC} ${LFLAG} $@.o -o $@

deroff: deroff.o
	${CC} ${LFLAG} $@.o -o $@

diffh: diffh.o
	${CC} ${LFLAG} $@.o -o $@

find: find.o
	${CC} ${LFLAG} $@.o -o $@

join: join.o
	${CC} ${LFLAG} $@.o -o $@

look: look.o
	${CC} ${LFLAG} $@.o -o $@

mesg: mesg.o
	${CC} ${LFLAG} $@.o -o $@

ptx: ptx.o
	${CC} ${LFLAG} $@.o -o $@

ranlib: ranlib.o
	${CC} ${LFLAG} $@.o -o $@

rev: rev.o
	${CC} ${LFLAG} $@.o -o $@

sleep: sleep.o
	${CC} ${LFLAG} $@.o -o $@

split: split.o
	${CC} ${LFLAG} $@.o -o $@

sum: sum.o
	${CC} ${LFLAG} $@.o -o $@

tabs: tabs.o
	${CC} ${LFLAG} $@.o -o $@

tc: tc.o
	${CC} ${LFLAG} $@.o -o $@

tk: tk.o
	${CC} ${LFLAG} $@.o -o $@

touch: touch.o
	${CC} ${LFLAG} $@.o -o $@

tr: tr.o
	${CC} ${LFLAG} $@.o -o $@

tsort: tsort.o
	${CC} ${LFLAG} $@.o -o $@

tty: tty.o
	${CC} ${LFLAG} $@.o -o $@

uniq: uniq.o
	${CC} ${LFLAG} $@.o -o $@

512restor: 512restor.o
	${CC} ${LFLAG} $@.o -o $@

fgrep: fgrep.o
	${CC} ${LFLAG} $@.o -o $@

sort: sort.o
	${CC} ${LFLAG} $@.o -o $@

iostat: iostat.o
	${CC} ${LFLAG} $@.o -o $@

units: units.o
	${CC} ${LFLAG} $@.o -o $@

.c.o:
	${CC} ${CFLAGS} ${FP} -c $*.c

512dumpdir.o:	512dumpdir.c
at.o:		at.c
basename.o:	basename.c
cal.o:		cal.c
cb.o:		cb.c
checkeq.o:	checkeq.c
checkobj.o:	checkobj.c
col.o:		col.c
comm.o:		comm.c
crypt.o:	crypt.c
cu.o:		cu.c
cu.3451A.o:	cu.3451A.c
deroff.o:	deroff.c
diffh.o:	diffh.c
find.o:		find.c
join.o:		join.c
look.o:		look.c
mesg.o:		mesg.c
ptx.o:		ptx.c
ranlib.o:	ranlib.c
rev.o:		rev.c
sleep.o:	sleep.c
split.o:	split.c
sum.o:		sum.c
tabs.o:		tabs.c
tc.o:		tc.c
tk.o:		tk.c
touch.o:	touch.c
tr.o:		tr.c
tsort.o:	tsort.c
tty.o:		tty.c
uniq.o:		uniq.c
512restor.o:	512restor.c
fgrep.o:	fgrep.c
sort.o:		sort.c
iostat.o:	iostat.c
units.o:	units.c
