#! /bin/csh -f
#
#	sendbug.sh	4.1	83/05/11
# Create a bug report and mail to '2bsd-bugs'.
#

onintr clean
/bin/cp /usr/ucb/bugformat /tmp/bug$$
/bin/vi /tmp/bug$$
if ($#argv == 0) then
	/bin/mail 2bsd-bugs\@BERKELEY < /tmp/bug$$
else
	/bin/mail $argv[1] < /tmp/bug$$
endif
clean:
/bin/rm -f /tmp/bug$$
