.TH GREEK 7
.SH NAME
greek \- graphics for extended TTY-37 type-box
.SH SYNOPSIS
\fBcat /usr/public/greek k\fP [ \(bv \(\fB\(emT\fPterminal ]
.SH DESCRIPTION
\fIGreek\fP gives the mapping from ascii to the 'shift out' graphics
in effect between SO and SI on model 37 Teletypes with a 128-character
type-box.  These are the default greek characters produced by \fInroff\fP.  
The file contains:
.PP
.ta \w'LAMBDA    'u +\w'123 'u +\w'123456789 'u +\w'integral    'u \
+\w'123 'u +\w'123456789 'u +\w'Lambda    'u +\w'123 'u
alpha	\(*a	A	beta	\(*b	B	gamma	\(*g	\\
.br
GAMMA	\(*G	G	delta	\(*d	D	DELTA	\(*D	W
.br
epsilon	\(*e	S	zeta	\(*z	Q	eta	\(*y	N
.br
THETA	\(*H	T	theta	\(*h	O	lambda	\(*l	L
.br
LAMBDA	\(*L	E	mu	\(*m	M	nu	\(*n	@
.br
xi	\(*c	X	pi	\(*p	J	PI	\(*P	P
.br
rho	\(*r	K	sigma	\(*s	Y	SIGMA	\(*S	R
.br
tau	\(*t	I	phi	\(*f	U	PHI	\(*F	F
.br
psi	\(*q	V	PSI	\(*Q	H	omega	\(*w	C
.br
OMEGA	\(*W	Z	nabla	\(gr	[	not	\(no	-
.br
partial	\(pd	]	integral	\(is	^
.SH FILES
/usr/public/greek
.SH SEE ALSO
troff(1)	
